import sys
import os
from typing import List, Dict, Any

from app.utils.task_utils import add_running_task, add_done_task
from app.lm.lm_utils import get_llm_client
from app.lm.embedding_utils import generate_embeddings
from app.clients.milvus_utils import get_milvus_client, create_hybrid_search_requests, hybrid_search
from app.core.logger import logger
from app.core.load_prompt import load_prompt
from dotenv import load_dotenv, find_dotenv

load_dotenv(find_dotenv())


def step_1_create_hyde_doc(rewritten_query: str) -> str:
    """
    Phase 1: Generates a hypothetical document using an LLM based on the user query.
    
    The core idea of HyDE is to leverage an LLM to generate a "fictional but relevant" document,
    then use the embedding of this document to retrieve actual chunks. This helps mitigate the
    semantic mismatch between short user queries and long documents.

    :param rewritten_query: The rewritten user query string.
    :return: The hypothetical document content generated by the LLM.
    """
    if not rewritten_query:
        logger.error("Step 1 Error: rewritten_query is empty")
        raise ValueError("rewritten_query cannot be empty")

    logger.info(f"Step 1: Starting hypothetical document generation (HyDE), Query: {rewritten_query}")
    try:
        llm = get_llm_client()
        # Load the prompt template to generate the hypothetical document.
        # This prompt typically guides the LLM: "Write a professional paragraph answering this query..."
        hyde_prompt = load_prompt("hyde_prompt", rewritten_query=rewritten_query)
        logger.debug(f"Step 1: Prompt loaded successfully, length: {len(hyde_prompt)}")
        # Invoke LLM to generate content
        response = llm.invoke(hyde_prompt)
        hyde_doc = response.content
         
        logger.info(f"Step 1: Hypothetical document generation completed, length: {len(hyde_doc)} characters")
        logger.debug(f"Step 1: Document preview: {hyde_doc[:50]}...")
         
        return hyde_doc

    except Exception as e:
        logger.error(f"Step 1: Failed to generate hypothetical document: {e}")
        raise e


def step_2_search_embedding_hyde(
    rewritten_query: str,
    hyde_doc: str,
    item_names: List[str] = None,
    req_limit: int = 10,
    top_k: int = 5,
    ranker_weights=(0.8, 0.2),  # Tuned weights biased towards dense vectors (0.8, 0.2)
    norm_score: bool = True,    # Normalization enabled by default
    output_fields: List[str] = ("chunk_id", "content", "item_name"),
) -> List[Dict[str, Any]]:
    """
    Phase 2: Generates embeddings using the "rewritten query + hypothetical document" context,
    and retrieves matching text chunks from the vector database.
     
    :param rewritten_query: The rewritten query.
    :param hyde_doc: The hypothetical document generated in Step 1.
    :param item_names: Product name list used for metadata filtering (item_name in [...]).
    :param req_limit: Candidate recall limit during Milvus search.
    :param top_k: Final Top-K results limit.
    :param ranker_weights: Weights distribution for hybrid retrieval (Dense, Sparse).
    :param norm_score: Whether to normalize scores.
    :param output_fields: Fields to return in results.
    :return: Retrieval results list.
    """
    if not rewritten_query:
        raise ValueError("rewritten_query cannot be empty")
    if not hyde_doc:
        raise ValueError("hyde_doc cannot be empty")
    # 1. Concatenate query and hypothetical document to form a richer semantic context
    combined_text = rewritten_query + " " + hyde_doc
    logger.info(f"Step 2: Concatenated Query + HyDE Doc, total length: {len(combined_text)}")
    # 2. Generate embeddings (Dense + Sparse)
    logger.info("Step 2: Generating hybrid embeddings...")
    embeddings = generate_embeddings([combined_text])
    # 3. Prepare Milvus retrieval
    collection_name = os.environ.get("CHUNKS_COLLECTION")
    if not collection_name:
        logger.error("Step 2 Error: Environment variable CHUNKS_COLLECTION not set")
        return []
         
    logger.info(f"Step 2: Preparing to execute hybrid search in collection '{collection_name}'")

    # Construct filtering expression (if product name limits exist)
    expr = None
    if item_names:
        # Quote item names to prevent potential syntax issues or injections
        quoted = ", ".join(f'"{v}"' for v in item_names)
        expr = f"item_name in [{quoted}]"
        logger.info(f"Step 2: Applying filtering criteria: {expr}")
    else:
        logger.info("Step 2: No product name filter specified; performing a full collection search")
    
    try:
        # Construct search requests
        reqs = create_hybrid_search_requests(
            dense_vector=embeddings.get("dense")[0],
            sparse_vector=embeddings.get("sparse")[0],
            expr=expr,
            limit=req_limit,
        )

        client = get_milvus_client()
        if not client:
            logger.error("Step 2 Error: Unable to connect to Milvus")
            return []

        # Execute hybrid search
        logger.info(f"Step 2: Executing hybrid search, Weights={ranker_weights}, TopK={top_k}")
        res = hybrid_search(
            client=client,
            collection_name=collection_name,
            reqs=reqs,
            ranker_weights=ranker_weights,
            norm_score=norm_score,
            limit=top_k,
            output_fields=list(output_fields),
        )
        hit_count = len(res[0]) if res and len(res) > 0 else 0
        logger.info(f"Step 2: Retrieval completed, found {hit_count} matching chunks")
         
        return res

    except Exception as e:
        logger.error(f"Step 2: Exception occurred during retrieval: {e}")
        return []

def node_search_embedding_hyde(state): 
    """
    HyDE (Hypothetical Document Embedding) Retrieval Node
    
    Core Concept: Generates a hypothetical answer (HyDE document) using an LLM,
    vectorizes it, and uses it for retrieval to resolve the semantic sparsity of short queries.
 
    Execution Steps:
    1. Parameter Extraction: Retrieve rewritten query and confirmed product names from session state.
    2. Generate Hypothetical Document (Step 1): Invoke LLM to write an ideal hypothetical answer.
    3. Hybrid Retrieval (Step 2):
       - Combine user query and hypothetical document, generating BGE-M3 dense and sparse embeddings.
       - Execute hybrid search in Milvus with product filtering, retrieving relevant chunks.
    4. Package Results: Return retrieved chunks and the hypothetical document to update the session state.
 
    :param state: Session state dictionary containing session_id, rewritten_query, item_names, etc.
    :return: Dictionary containing hyde_embedding_chunks (retrieved results) and hyde_doc (hypothetical document).
    """
    logger.info("---HyDE (Hypothetical Document Retrieval) node starting execution---")
    # Mark task start state
    add_running_task(state["session_id"], sys._getframe().f_code.co_name, state.get("is_stream"))
 
    # 1. Parameter extraction and validation
    # Prioritize rewritten query, fallback to the original query if absent
    rewritten_query = state.get("rewritten_query")
    if not rewritten_query:
        rewritten_query = state.get("original_query")
     
    if not rewritten_query:
        logger.error("HyDE node error: No valid user query found (both rewritten_query and original_query are empty)")
        return {}
 
    item_names = state.get("item_names")
    logger.info(f"HyDE retrieval inputs: query='{rewritten_query}', item_names={item_names}")
 
    # Phase 1: Generate hypothetical document
    hyde_doc = ""
    try:
        logger.info("Step 1: Starting hypothetical document generation (HyDE Doc)...")
        hyde_doc = step_1_create_hyde_doc(rewritten_query)
        logger.info(f"Step 1: Hypothetical document generated successfully (length: {len(hyde_doc)})")
        logger.debug(f"Hypothetical document preview: {hyde_doc[:100]}...")
    except Exception as e:
        logger.error(f"Step 1 (Generate hypothetical document) exception occurred: {e}", exc_info=True)
        # HyDE generation failures are non-blocking errors; we can degrade gracefully and return an empty state
        return {}
 
    # Phase 2: Search chunks using 'rewritten query + hypothetical document'
    # Phase 2: Search chunks using 'rewritten query + hypothetical document'
    try:
        logger.info("Step 2: Performing Milvus hybrid retrieval based on hypothetical document...")
        res = step_2_search_embedding_hyde(
            rewritten_query=rewritten_query,
            hyde_doc=hyde_doc,
            item_names=item_names,
            top_k=5,
        )
        hit_count = len(res[0]) if res and len(res) > 0 else 0
        logger.info(f"Step 2: Retrieval completed, recalled {hit_count} relevant chunks")
        if hit_count > 0:
            # Output first hit sample for debugging
            first_hit = res[0][0]
            score = first_hit.get("distance")
            content_preview = first_hit.get("entity", {}).get("content", "")[:30]
            logger.debug(f"Top 1 Result: Score={score}, Content='{content_preview}...'")
 
        return {
            "hyde_embedding_chunks": res[0] if res else [],
            "hyde_doc": hyde_doc,
        }
    except Exception as e:
        logger.error(f"Step 2 (Vector generation and retrieval) exception occurred: {e}", exc_info=True)
        return {}
    finally:
        # Ensure task is marked completed regardless of success/failure
        add_done_task(state["session_id"], sys._getframe().f_code.co_name, state.get("is_stream"))
        logger.info("---HyDE node processing finished---")
         
         