import os 
import sys 
from typing import List, Dict, Any 

# Import Milvus-related dependencies
from pymilvus import DataType 

# Import custom modules
from app.import_process.agent.state import ImportGraphState 
from app.clients.milvus_utils import get_milvus_client 
from app.utils.task_utils import add_running_task 
from app.core.logger import logger 
from app.conf.milvus_config import milvus_config 
from app.utils.escape_milvus_string_utils import escape_milvus_string 

# Read chunks collection name from config file to decouple from configs, easing environment switching
CHUNKS_COLLECTION_NAME = milvus_config.chunks_collection 

# ========================================== 
# Milvus Chunk Data Persistence Core Node 
# Core Capabilities: Batch-persists text chunks vector-enriched upstream into Milvus, implementing idempotent writes. 
# Core Design: 
# 1. Idempotency: Deletes old data sharing the same 'item_name' prior to insertion, preventing redundant record footprints. 
# 2. Automated Table Creation: Auto-provisions Schema and Vector Indexes if the collection is non-existent, avoiding manual initialization. 
# 3. Data Validation: Pre-validates chunk viability and vector field integrity to keep dirty records from hitting the database. 
# 4. Primary Key Backfilling: Backfills the auto-incremented 'chunk_id' generated by Milvus into chunks for downstream business use cases. 
# Upstream Dependency: BGE-M3 vectorization node (which supplies the 'dense_vector' and 'sparse_vector' fields). 
# ========================================== 

def step_1_check_input(state: Dict[str, Any]) -> tuple[List[Dict[str, Any]], int]: 
    """
    Step 1: Input Data Validity Verification (Mandatory pre-persistence check)
    
    Core Validation Items:
    1. 'chunks' is non-empty and must be a list data type.
    2. Chunks must contain the core 'dense_vector' field (a mandatory output from the upstream embedding node).
    3. Extract vector dimensional depths to provide baseline parameters for collection creation/index provisioning.
    
    Parameters:
    state: Dict[str, Any] - The global pipeline state object containing the raw 'chunks' payload.
    
    Returns:
    tuple - (Validated list of chunks, dense vector dimensional depth)
    
    Exceptions:
    Raises a ValueError if any validation item fails, terminating the persistence pipeline to safeguard against dirty data processing.
    """ 
    # Extract the chunk records awaiting data persistence
    chunks_json_data = state.get("chunks") 
    
    # Validation 1: Check if chunks exists
    if not chunks_json_data: 
        logger.error("Milvus persistence validation failed: 'chunks' field is missing or empty in state.") 
        raise ValueError("Error: Chunks is empty; unable to execute Milvus persistence.") 
        
    # Validation 2: Ensure chunks is formatted as a non-empty list
    if not isinstance(chunks_json_data, list) or len(chunks_json_data) == 0: 
        logger.error("Milvus persistence validation failed: 'chunks' is either not a list data type or an empty list.") 
        raise ValueError("Error: Incorrect chunks data format; it must be a non-empty list.") 
        
    # Validation 3: Ensure chunks contain the 'dense_vector' field (the core artifact of the upstream embedding node)
    first_chunk = chunks_json_data[0] 
    if 'dense_vector' not in first_chunk: 
        logger.error("Milvus persistence validation failed: Chunks are missing the 'dense_vector' field; the upstream embedding node may have failed.") 
        raise ValueError("Error: Missing 'dense_vector' field in data payload. Please check the execution status of the upstream embedding node.") 
        
    # Extract vector dimensional depth and item name for downstream collection creation and logging trace visibility
    vector_dimension = len(first_chunk['dense_vector']) 
    item_name = first_chunk.get('item_name', 'Unknown Item Name') 
    
    logger.info( 
        f"Milvus persistence validation passed. Chunks awaiting storage: {len(chunks_json_data)} | " 
        f"Vector Dimension: {vector_dimension} | Item Name: {item_name}" 
    ) 
    return chunks_json_data, vector_dimension

def create_collection(client, collection_name: str, vector_dimension: int): 
    """
    Helper function: Automated Milvus collection and index provisioning.
    
    Core Logic:
    1. Define Collection Schema: Includes business meta-fields and hybrid vector fields, using an auto-increment primary key 'chunk_id'.
    2. Build Vector Indexes: Leverages HNSW for the dense vector and a dedicated inverted index for the sparse vector.
    
    Parameters:
    client - Connected MilvusClient instance.
    collection_name: str - The name of the collection to create.
    vector_dimension: int - Dense vector dimensional depth (must align with the embedding model).
    """ 
    # 1. Create Schema: Enable auto_id + dynamic fields to accommodate flexible business scaling requirements
    schema = client.create_schema(auto_id=True, enable_dynamic_fields=True) 
    
    # 2. Add Fields: Business fields + Primary Key + Hybrid Vector fields, tailored to production data types
    schema.add_field(field_name="chunk_id", datatype=DataType.INT64, is_primary=True, auto_id=True) 
    schema.add_field(field_name="content", datatype=DataType.VARCHAR, max_length=65535)       # Chunk content string
    schema.add_field(field_name="title", datatype=DataType.VARCHAR, max_length=65535)         # Chunk title
    schema.add_field(field_name="parent_title", datatype=DataType.VARCHAR, max_length=65535)  # Parent heading/title
    schema.add_field(field_name="part", datatype=DataType.INT8)                               # Chunk slice/part number
    schema.add_field(field_name="file_title", datatype=DataType.VARCHAR, max_length=65535)    # Source file title
    schema.add_field(field_name="item_name", datatype=DataType.VARCHAR, max_length=65535)     # Item/Subject name (Idempotency target key)
    schema.add_field(field_name="sparse_vector", datatype=DataType.SPARSE_FLOAT_VECTOR)       # Sparse vector representations
    schema.add_field(field_name="dense_vector", datatype=DataType.FLOAT_VECTOR, dim=vector_dimension) # Dense vector representations

    # For the BGE-M3 model:
    # Its output dimensionality is fixed at 1024.
    # Therefore, your configurations must read:
    # ```
    # vector_dimension must be 1024, cannot be changed!
    # schema.add_field(..., dim=vector_dimension)
    # ``` 
    # (If using BGE-base, it is 768; if BGE-small, it is 384. This is entirely dictated by the model's architecture.)

    # 3. Build Index Parameters: Provision indexes for vector attributes to accelerate search scaling performance
    index_params = client.prepare_index_params() 
    
    # Optimized Dense Vector Index: HNSW + COSINE (Restoring optimal execution settings)
    index_params.add_index( 
        field_name="dense_vector", 
        index_name="dense_vector_index", 
        # HNSW (Hierarchical Navigable Small World) is currently the highest-performing and most widely used 
        # graph-based index, providing lightning-fast search speeds and extreme precision.
        index_type="HNSW", 
        # Use COSINE similarity for dense vector distance metric calculations
        metric_type="COSINE", 
        # M: Maximum number of connection links per node in the graph (commonly 16-64)
        # efConstruction: Search scope during index construction (larger values increase build time but improve precision, commonly 100-200)
        params={"M": 16, "efConstruction": 200} 
    ) 
    
    # Sparse Vector Index: Dedicated SPARSE_INVERTED_INDEX + IP, turning off quantization to guarantee precision
    index_params.add_index( 
        field_name="sparse_vector", 
        index_name="sparse_vector_index", 
        # Sparse Inverted Index: An inverted index purpose-built for sparse vectors (e.g., text TF-IDF vectors or keyword 
        # weight vectors, where most elements are 0 and only a few dimensions hold values). It is the standard index type for sparse retrieval.
        index_type="SPARSE_INVERTED_INDEX", 
        # IP (Inner Product): If the vector represents "text semantic vector + keyword weights" where length dictates the 
        # correlation strength between the text and topic, using IP captures both "semantic matching degree" and "correlation intensity".
        metric_type="IP", 
        # DAAT_MAXSCORE is a highly efficient algorithm for sparse retrieval. quantization="none" ensures no loss in sparse vector weights.
        params={"inverted_index_algo": "DAAT_MAXSCORE", "normalize": True, "quantization": "none"} 
    ) 
    
    # 4. Create Collection: Merge Schema and Index parameters to finalize multi-vector initialization in a single transaction
    client.create_collection(collection_name=collection_name, schema=schema, index_params=index_params) 
    logger.info(f"Milvus collection created successfully: {collection_name} | Vector Dimension: {vector_dimension}")

def step_2_prepare_collection(vector_dimension: int): 
    """
    Step 2: Milvus Client Connection and Collection Onboarding
    
    Core Logic:
    1. Fetch the Milvus singleton client instance and validate connection viability.
    2. Auto-create the collection (Schema + Indexes) if it does not exist; reuse it directly if it already exists.
    
    Parameters:
    vector_dimension: int - Dense vector dimensional depth (extracted in Step 1).
    
    Returns:
    MilvusClient - An active client instance with the target collection onboarded and ready.
    
    Exceptions:
    Raises a ValueError to terminate the pipeline if client retrieval fails or the collection name is unconfigured.
    """ 
    logger.info(f"Starting Milvus environment provisioning. Target collection: {CHUNKS_COLLECTION_NAME}") 
    
    # 1. Fetch the Milvus singleton client instance and validate connection viability
    client = get_milvus_client() 
    if client is None: 
        logger.error("Milvus client retrieval failed: get_milvus_client() returned null; connection might be broken.") 
        raise ValueError("Milvus connection failed: get_milvus_client() returned None.") 
        
    # 2. Verify collection name settings configuration
    if not CHUNKS_COLLECTION_NAME: 
        logger.error("Milvus collection name unconfigured: CHUNKS_COLLECTION_NAME is empty.") 
        raise ValueError("The CHUNKS_COLLECTION name configuration is missing.") 
        
    # 3. Auto-create the collection if it is non-existent
    if not client.has_collection(collection_name=CHUNKS_COLLECTION_NAME): 
        logger.info(f"Milvus collection '{CHUNKS_COLLECTION_NAME}' does not exist. Starting automated Schema and Index provisioning.") 
        create_collection(client, CHUNKS_COLLECTION_NAME, vector_dimension) 
    else: 
        logger.info(f"Milvus collection '{CHUNKS_COLLECTION_NAME}' already exists; reusing it directly.") 
        
    return client

def _clear_chunks_by_item_name(client, collection_name: str, item_name: str):
    """
    Internal Core Function: Deletes historical chunk data associated with a specific item_name from Milvus.
    
    :param client: MilvusClient instance.
    :param collection_name: Name of the target collection.
    :param item_name: Name of the product/item whose old records should be purged.
    :raise ValueError: Thrown if the purge fails, terminating the ingestion pipeline to guarantee idempotency.
    """
    # Preprocessing: Trim whitespace and return early if values are missing
    i_name = (item_name or "").strip()
    if not i_name:
        logger.warning("Milvus single item cleanup skipped: item_name is empty.")
        return
    if not collection_name:
        logger.warning("Milvus single item cleanup skipped: collection_name is not configured.")
        return
        
    try:
        # If the collection does not exist, no data cleanup is required
        if not client.has_collection(collection_name=collection_name):
            logger.info(f"Milvus single item cleanup skipped: Collection '{collection_name}' does not exist.")
            return
            
        # 1. Safely escape the item name to prevent parsing errors inside the filter expression
        safe_item_name = escape_milvus_string(i_name)
        filter_expr = f'item_name == "{safe_item_name}"'
        logger.info(f"Milvus idempotency purge: Commencing deletion of legacy records under item_name='{i_name}' in collection '{collection_name}'.")
        
        # 2. Execute the deletion operation
        client.delete(collection_name=collection_name, filter=filter_expr)
        
        # 3. Force a flush to guarantee the deletion takes effect immediately (bypasses Milvus async latency)
        if hasattr(client, "flush"):
            try:
                client.flush(collection_name=collection_name)
            except Exception as e:
                logger.warning(f"Milvus idempotency purge: flush operation failed, continuing main workflow | Error: {str(e)}")
                
        logger.info(f"Milvus idempotency purge completed: Successfully deleted legacy records for item_name='{i_name}'.")
        
    except Exception as e:
        logger.error(f"Milvus idempotency purge failed for item_name='{i_name}' | Error: {str(e)}", exc_info=True)
        raise ValueError(f"Idempotency cleanup failed (item_name={i_name}): {e}")

def step_3_clean_old_data(client, chunks_json_data: List[Dict[str, Any]]): 
    """
    Step 3: Idempotency Execution - Purging historical records based on item_name
    
    Core Design:
    Purges all historical chunks sharing the same 'item_name' prior to inserting new records, 
    ensuring multiple execution cycles retain only the most up-to-date data state. 
    Supports batch cleanup across multiple item_names, automatically deduplicating targets to avoid redundant operations.
    
    Parameters:
    client - Connected MilvusClient instance.
    chunks_json_data: List[Dict[str, Any]] - The payload list of chunks awaiting database insertion.
    """ 
    # Extract and deduplicate item_names to avoid redundant cleanup cycles on the exact same product profiles
    # - Execution Order: Loop evaluation (for) -> Condition filtering (if) -> Value extraction output (name).
    # - Purpose of the Walrus Operator (:=): In step ② (the condition check), it concurrently populates the processed 
    #   string into the 'name' variable. If 'name' resolves to an empty string "" (which evaluates to False in Python), 
    #   the condition fails, step ③ is skipped, and the null/empty entry is thrown away.
    item_names = sorted({ 
        name  # ③ Step Three: If not blocked by the 'if' guard, drop the 'name' value into the set container
        for x in chunks_json_data or []  # ① Step One: Begin the loop, extracting document 'x'
        if (name := str(x.get("item_name", "")).strip())  # ② Step Two: Extract -> Strip -> Assign to 'name' -> Evaluate if 'name' is non-empty
    }) 

    # Skip cleanup if no valid item_names are parsed
    if not item_names: 
        logger.warning("Milvus idempotency cleanup skipped: No valid 'item_name' found across data chunks.") 
        return 

    # Log an alert tracking multi-subject scenarios
    if len(item_names) > 1: 
        logger.warning(f"Milvus idempotency cleanup alert: Detected multiple distinct item_names; purging sequentially: {item_names}") 

    # Loop through unique item_names to sequentially scrub historical data records
    for i_name in item_names: 
        _clear_chunks_by_item_name(client, CHUNKS_COLLECTION_NAME, i_name)
        
def _clear_chunks_by_item_name(client, collection_name: str, item_name: str):
    """
    Internal Core Function: Deletes historical chunk data associated with a specific item_name from Milvus.
    
    :param client: MilvusClient instance.
    :param collection_name: Name of the target collection.
    :param item_name: Name of the product/item whose old records should be purged.
    :raise ValueError: Thrown if the purge fails, terminating the ingestion pipeline to guarantee idempotency.
    """
    # Preprocessing: Trim whitespace and return early if values are missing
    i_name = (item_name or "").strip()
    if not i_name:
        logger.warning("Milvus single item cleanup skipped: item_name is empty.")
        return
    if not collection_name:
        logger.warning("Milvus single item cleanup skipped: collection_name is not configured.")
        return
        
    try:
        # If the collection does not exist, no data cleanup is required
        if not client.has_collection(collection_name=collection_name):
            logger.info(f"Milvus single item cleanup skipped: Collection '{collection_name}' does not exist.")
            return
            
        # 1. Safely escape the item name to prevent parsing errors inside the filter expression
        safe_item_name = escape_milvus_string(i_name)
        filter_expr = f'item_name == "{safe_item_name}"'
        logger.info(f"Milvus idempotency purge: Commencing deletion of legacy records under item_name='{i_name}' in collection '{collection_name}'.")
        
        # 2. Execute the deletion operation
        client.delete(collection_name=collection_name, filter=filter_expr)
        
        # 3. Force a flush to guarantee the deletion takes effect immediately (bypasses Milvus async latency)
        if hasattr(client, "flush"):
            try:
                client.flush(collection_name=collection_name)
            except Exception as e:
                logger.warning(f"Milvus idempotency purge: flush operation failed, continuing main workflow | Error: {str(e)}")
                
        logger.info(f"Milvus idempotency purge completed: Successfully deleted legacy records for item_name='{i_name}'.")
        
    except Exception as e:
        logger.error(f"Milvus idempotency purge failed for item_name='{i_name}' | Error: {str(e)}", exc_info=True)
        raise ValueError(f"Idempotency cleanup failed (item_name={i_name}): {e}")
     
def step_4_insert_data(client, chunks_json_data: List[Dict[str, Any]]) -> List[Dict[str, Any]]: 
    """
    Step 4: Batch-insert chunk data into Milvus and backfill primary keys
    
    Core Logic:
    1. Remove manual chunk_ids: Since auto_id=True is enabled, Milvus automatically generates the primary keys. Removing them avoids collisions.
    2. Batch-insert data: Boosts persistence insertion throughput efficiency and minimizes Milvus transactional connection overhead.
    3. Backfill chunk_ids: Backfills the auto-incremented primary keys generated by Milvus into the chunk records for downstream business usage.
    
    Parameters:
    client - Connected MilvusClient instance.
    chunks_json_data: List[Dict[str, Any]] - The payload list of chunks awaiting database insertion.
    
    Returns:
    List[Dict[str, Any]] - The list of chunks now enriched with backfilled 'chunk_id' fields.
    """ 
    # 1. Preprocess data: Strip any manual chunk_id fields to prevent conflicts with the Milvus auto-increment primary key
    data_to_insert = [] 
    for item in chunks_json_data: 
        item_copy = item.copy() 
        if isinstance(item_copy, dict) and "chunk_id" in item_copy: 
            item_copy.pop("chunk_id", None) 
        data_to_insert.append(item_copy) 
        
    logger.info(f"Milvus data insertion: Prepared {len(data_to_insert)} chunk records. Starting batch insertion.") 
    
    # 2. Execute batch insertion transaction mutation
    insert_result = client.insert(collection_name=CHUNKS_COLLECTION_NAME, data=data_to_insert) 
    insert_count = insert_result.get('insert_count', 0) 
    logger.info(f"Milvus data insertion completed: Successfully inserted {insert_count} records. Insertion receipt metadata: {insert_result}") 
    
    # 3. Primary key backfilling: Map the auto-generated chunk_ids returned by Milvus back to the original source chunk instances
    inserted_ids = insert_result.get('ids', []) 
    if inserted_ids and len(inserted_ids) == len(chunks_json_data): 
        logger.info(f"Milvus primary key backfilling: Starting to write {len(inserted_ids)} auto-incremented chunk_ids back into chunk memory records.") 
        for idx, item in enumerate(chunks_json_data): 
            item['chunk_id'] = str(inserted_ids[idx]) 
        logger.info("Milvus primary key backfilling completed: All chunk objects are now bound with persistent chunk_ids.") 
    else: 
        logger.warning(f"Milvus primary key backfilling failed: The number of generated database IDs ({len(inserted_ids)}) does not match the input chunk array payload count ({len(chunks_json_data)}).") 
        
    return chunks_json_data

def node_import_milvus(state: Dict[str, Any]) -> Dict[str, Any]: 
    """
    LangGraph Core Node: Main Pipeline for Milvus Chunk Data Persistence
    
    Execution Pipeline (Sequential execution with step-by-step verification to ensure data consistency):
    1. Input Validation: Verifies chunk viability and vector field integrity, extracting vector dimensional depths.
    2. Environment Provisioning: Connects to Milvus and auto-creates Schema + Indexes if the collection does not exist.
    3. Idempotent Cleanup: Purges historical records sharing the same 'item_name' to prevent duplicate records.
    4. Batch Insertion: Preprocesses data for batch persistence, backfilling Milvus-generated auto-incremented 'chunk_id' fields.
    5. State Synchronization: Flushes the chunk_id-enriched chunks back into the global state for consumption by downstream nodes.
    
    Parameters:
    state: Dict[str, Any] - The global pipeline state object containing chunks, task_id, and other data payload properties.
    
    Returns:
    Dict[str, Any] - The updated state object, where the chunks field now contains backfilled 'chunk_id' metrics.
    
    Exception Handling:
    Any failure within individual steps will raise a ValueError, terminating node execution to safeguard against dirty data writes.
    """ 
     # Retrieve the current node name for task monitoring and logging signatures
    current_node = sys._getframe().f_code.co_name 
    logger.info(f">>> Starting execution of LangGraph node: {current_node} (Milvus Chunk Data Persistence)") 
    
    # Mark task execution status for frontend progress dashboard displays and task monitoring tracking
    add_running_task(state["task_id"], current_node) 
    logger.info("--- Milvus Chunk Data Persistence Pipeline Triggered ---") 
    
    try: 
        # Step 1: Input data validity and payload structure verification
        chunks_json_data, vector_dimension = step_1_check_input(state) 
        
        # Step 2: Milvus client link orchestration + collection onboarding (Automated Table Creation)
        client = step_2_prepare_collection(vector_dimension) 
        
        # Step 3: Idempotency execution - Purging historical records matching the same 'item_name'
        step_3_clean_old_data(client, chunks_json_data) 
        
        # Step 4: Batch insertion of data payloads + primary key chunk_id backfilling mutations
        updated_chunks = step_4_insert_data(client, chunks_json_data) 
        
        # Step 5: Update the global state, passing backfilled chunk records to downstream consumers
        state["chunks"] = updated_chunks 
        logger.info("--- Milvus Chunk Data Persistence Pipeline Completed ---") 
        
    except Exception as e: 
        logger.error(f"Milvus chunk persistence node execution failed: {str(e)}", exc_info=True) 
        raise ValueError(f"An error occurred during the Milvus import pipeline: {e}") 
        
    return state

#==============unit test ================

if __name__ == '__main__': 
    # --- Unit Testing --- 
    # Purpose: Validates the complete pipeline execution of the Milvus import node, 
    # including connection setup, collection provisioning, historical data cleanup, and new record insertion. 
    import sys 
    import os 
    from dotenv import load_dotenv 

    # Load environment variables (automatically targets the .env file in the project root directory) 
    current_dir = os.path.dirname(os.path.abspath(__file__)) 
    project_root = os.path.dirname(os.path.dirname(current_dir)) 
    load_dotenv(os.path.join(project_root, ".env")) 

    # Construct mock testing data payloads
    dim = 1024 
    test_state = { 
        "task_id": "test_milvus_task", 
        "chunks": [ 
            { 
                "content": "Milvus Test Text Content 1", 
                "title": "Test Section Title", 
                "item_name": "Test_Project_Milvus", # An item_name must be supplied for idempotency validation cleanup mutations 
                "parent_title": "test.pdf", 
                "part": 1, 
                "file_title": "test.pdf", 
                "dense_vector": [0.1] * dim,          # Mocked high-dimensional Dense Vector array 
                "sparse_vector": {1: 0.5, 10: 0.8}    # Mocked variable-length Sparse Vector weights map 
            } 
        ] 
    } 

    print("Running Milvus import node execution test harness...") 
    try: 
        # Check mandatory infrastructure environment variables 
        if not os.getenv("MILVUS_URL"): 
            print("❌ MILVUS_URL environment variable is missing; cannot connect to Milvus endpoint.") 
        elif not os.getenv("CHUNKS_COLLECTION"): 
            print("❌ CHUNKS_COLLECTION environment variable is unconfigured.") 
        else: 
            # Invoke the core node orchestration handler 
            result_state = node_import_milvus(test_state) 
            
            # Assert execution outcomes and inspect mutated payload footprints 
            chunks = result_state.get("chunks", []) 
            if chunks and chunks[0].get("chunk_id"): 
                print(f"✅ Milvus persistence test harness passed. Generated chunk tracking ID: {chunks[0]['chunk_id']}") 
            else: 
                print("❌ Test failure alert: System failed to fetch and backfill the database chunk_id.") 
                
    except Exception as e: 
        print(f"❌ Test runner execution crashed: {e}")